name: dcflight_cli
description: DCFlight CLI - Development tools for DCFlight framework
version: 0.0.1
# repository: https://github.com/squirelboy360/dcflight

environment:
  sdk: ^3.6.1

executables:
  dcf: dcflight_cli

dependencies:
  args: ^2.6.0              # Command line argument parsing
  path: ^1.9.1              # File path manipulation

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
